spring.application.name=ATB-2526-SmartBank 
spring.datasource.url=jdbc:postgresql://localhost:5432/ATB-2526-DataBase
spring.datasource.username=postgres
spring.datasource.password=2004
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8181

jwt.secret=8f4d7c91a2b5e8f1c3d6a9b7e4f2c8d1a5b9e6f3c7d2a1456789abcdef1234567895885889558hueh8
jwt.expiration=86400000